### ISSUE TITLE
FileExistsError: [WinError 183] Cannot create a file because it already exists: './dynamicrafter_1024_v1/'

### ISSUE THREAD

**Issue by protector131090** [Doubiiu/DynamiCrafter#14]
Please help! if i download the file i get the rror. If o dont and let the code download its taking 5 hours! 
How do i modify the code so it wont redownload the model?!
Traceback (most recent call last):
  File "gradio_app.py", line 170, in <module>
    dynamicrafter_iface = dynamicrafter_demo(result_dir, args.res)
  File "gradio_app.py", line 47, in dynamicrafter_demo
    image2video = Image2Video(result_dir, resolution=resolution)
  File "S:\DynamiCrafter\scripts\gradio\i2v_test.py", line 16, in __init__
    self.download_model()
  File "S:\DynamiCrafter\scripts\gradio\i2v_test.py", line 97, in download_model
    os.makedirs('./dynamicrafter_'+str(self.resolution[1])+'_v1/')
  File "S:\DynamiCrafter\lib\os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [WinError 183] Cannot create a file because it already exists: './dynamicrafter_1024_v1/'

**Comment by Doubiiu** [comment]
Hi I have updated the `i2v_test.py` file to fix the corresponding bug. Sorry for the incovenience caused.
