### ISSUE TITLE
module 'comfy.sd' has no attribute 'CLIPType'

### ISSUE THREAD

**Issue by YikaPanic** [Doubiiu/DynamiCrafter#88]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "E:\Stable-Diffusion\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 155, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable-Diffusion\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 85, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable-Diffusion\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 78, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Stable-Diffusion\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DynamiCrafterWrapper\nodes.py", line 164, in loadmodel
    clip_type = comfy.sd.CLIPType.STABLE_DIFFUSION
                ^^^^^^^^^^^^^^^^^
AttributeError: module 'comfy.sd' has no attribute 'CLIPType'

When I try to run this workflow in example，using stable version of comfy ui 01/2024 I encountered this issue. I don't know how to tackle it

**Comment by Doubiiu** [comment]
Hi. As I am not familiar with the ComfyUI stuff, please seek help from the original repo.
